name: Angular
on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened, locked ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  code_analysis:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:ci
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS
          fail_ci_if_error: true
          files: coverage/mds-desktop/cobertura-coverage.xml
          verbose: true
